jobs:
    - job:
      displayName: ubuntu-16.04
      pool:
        vmImage: 'ubuntu-16.04'

      steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: |
          wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml
          conda env create -q -n qiime2-dev --file qiime2-latest-py36-linux-conda.yml
        displayName: Set up Qiime 2

      - bash: |
          source activate qiime2-dev
          conda install --yes --quiet --name qiime2-dev -c bioconda -c conda-forge cobra umap-learn jinja2 pyarrow flake8 loguru
        displayName: Install required packages
      - bash: |
          source activate qiime2-dev
          conda install --yes --quiet --name qiime2-dev -c ibmdecisionoptimization cplex
        displayName: Install CPLEX test distribution
      - bash: |
          source activate qiime2-dev
          pip install .
          qiime dev refresh-cache
        displayName: Install q2-micom
      - bash: |
          source activate qiime2-dev
          pip install pytest pytest-cov pytest-azurepipelines
          pytest
        displayName: Run tests
      - script: |
          source activate qiime2-dev
          pip uninstall -y pytest-azurepipelines
          pip install pytest-cov
          pytest --cov
          bash <(curl -s https://codecov.io/bash)
        displayName: "Upload to codecov.io"


    - job:
      displayName: macOS-10.13
      pool:
        vmImage: 'macOS-10.13'

      steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: |
          wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-osx-conda.yml
          conda env create -q -n qiime2-dev --file qiime2-latest-py36-osx-conda.yml
        displayName: Set up Qiime 2

      - bash: |
          source activate qiime2-dev
          conda install --yes --quiet --name qiime2-dev -c bioconda -c conda-forge cobra umap-learn jinja2 pyarrow flake8 loguru
        displayName: Install required packages
      - bash: |
          source activate qiime2-dev
          conda install --yes --quiet --name qiime2-dev -c ibmdecisionoptimization cplex
        displayName: Install CPLEX test distribution
      - bash: |
          source activate qiime2-dev
          pip install .
          qiime dev refresh-cache
        displayName: Install q2-micom
      - bash: |
          source activate qiime2-dev
          flake8
        displayName: "Run flake8"
      - bash: |
          source activate qiime2-dev
          pip install pytest pytest-azurepipelines
          pytest
        displayName: Run tests
